name: Generate Definition File

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Full git history for commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run generate script
        run: npm run generate:definitions

      - name: Run sponsor script
        run: npm run generate:sponsors
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: ${{ secrets.SPONSORKIT_GITHUB_LOGIN }}
          SPONSORKIT_OPENCOLLECTIVE_SLUG: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_SLUG }}
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_KEY }}

      - name: Check for changes
        id: check-changes
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Git status output:"
          git status --porcelain
          echo "All git status (including untracked):"
          git status --porcelain --untracked-files=all
          if [[ -n "$(git status --porcelain --untracked-files=all)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected!"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push if changed
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "chore: generate definition file [skip ci]"
          git push
